GET http://localhost:4000/result

###
POST http://localhost:4000/get-result
Content-Type: application/json

{
  "geneDescription": "AFFX-BioB-5_st (endogenous control)",
  "accessionNo": "AFFX-BioB-5_st",
  "dob": 1960,
  "country": "pakistan",
  "avc": 44,
  "gender": "f",
  "climaticCondition": "Hot",
  "diseases": "hypertension",
  "stages": 1,
  "startAge": 32,
  "disLifeExp": 56,
  "inherited": "y",
  "smage": 35,
  "avsmexp": 73
}

###

GET http://localhost:4000/

